import type { Metadata } from 'next';
import { Rajdhani } from 'next/font/google';

import { ThirdwebProvider } from '@/components/ThirdwebProvider';
import { Sepolia } from '@thirdweb-dev/chains';

import './globals.css';
import { GlobalContextProvider } from '@/context';

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// This is the chain your dApp will work on.
// Change this to the chain your app is built for.
// You can also import additional chains from `@thirdweb-dev/chains` and pass them directly.
const activeChain = { Sepolia };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThirdwebProvider
      activeChain={Sepolia}
      clientId={process.env.NEXT_PUBLIC_CLIENT_ID}
    >
      <html lang='en'>
        <body className={rajdhani.className}>
          <GlobalContextProvider>{children}</GlobalContextProvider>
        </body>
      </html>
    </ThirdwebProvider>
  );
}
